/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as InterkommunaltSamarbeidKartleggingRouteImport } from './routes/interkommunalt-samarbeid-kartlegging'
import { Route as KommuneokonomiRadgivningRouteImport } from './routes/kommuneokonomi-radgivning'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as PersonvernRouteImport } from './routes/personvern'
import { Route as TakkRouteImport } from './routes/takk'
import { Route as EksperterRogerAntonsenRouteImport } from './routes/eksperter/roger-antonsen'
import { Route as FagomraderSlugRouteImport } from './routes/fagomrader/$slug'
import { Route as GuideInterkommunaltSamarbeidNorgeRouteImport } from './routes/guide/interkommunalt-samarbeid-norge'
import { Route as GuideKommuneokonomiNorskeKommunerRouteImport } from './routes/guide/kommuneokonomi-norske-kommuner'
import { Route as IMediaIndexRouteImport } from './routes/i-media/index'
import { Route as IMediaSlugRouteImport } from './routes/i-media/$slug'
import { Route as InspirasjonIndexRouteImport } from './routes/inspirasjon/index'
import { Route as InspirasjonSlugRouteImport } from './routes/inspirasjon/$slug'
import { Route as PublikasjonerIndexRouteImport } from './routes/publikasjoner/index'
import { Route as PublikasjonerParamRouteImport } from './routes/publikasjoner/$param'
import { Route as RapportSlugRouteImport } from './routes/rapport/$slug'
import { Route as RapportarkivIndexRouteImport } from './routes/rapportarkiv/index'
import { Route as RapportarkivYearRouteImport } from './routes/rapportarkiv/$year'
import { Route as TemaSlugRouteImport } from './routes/tema/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const InterkommunaltSamarbeidKartleggingRoute =
  InterkommunaltSamarbeidKartleggingRouteImport.update({
    id: '/interkommunalt-samarbeid-kartlegging',
    path: '/interkommunalt-samarbeid-kartlegging',
    getParentRoute: () => rootRouteImport,
  } as any)
const KommuneokonomiRadgivningRoute =
  KommuneokonomiRadgivningRouteImport.update({
    id: '/kommuneokonomi-radgivning',
    path: '/kommuneokonomi-radgivning',
    getParentRoute: () => rootRouteImport,
  } as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonvernRoute = PersonvernRouteImport.update({
  id: '/personvern',
  path: '/personvern',
  getParentRoute: () => rootRouteImport,
} as any)
const TakkRoute = TakkRouteImport.update({
  id: '/takk',
  path: '/takk',
  getParentRoute: () => rootRouteImport,
} as any)
const EksperterRogerAntonsenRoute = EksperterRogerAntonsenRouteImport.update({
  id: '/eksperter/roger-antonsen',
  path: '/eksperter/roger-antonsen',
  getParentRoute: () => rootRouteImport,
} as any)
const FagomraderSlugRoute = FagomraderSlugRouteImport.update({
  id: '/fagomrader/$slug',
  path: '/fagomrader/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideInterkommunaltSamarbeidNorgeRoute =
  GuideInterkommunaltSamarbeidNorgeRouteImport.update({
    id: '/guide/interkommunalt-samarbeid-norge',
    path: '/guide/interkommunalt-samarbeid-norge',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuideKommuneokonomiNorskeKommunerRoute =
  GuideKommuneokonomiNorskeKommunerRouteImport.update({
    id: '/guide/kommuneokonomi-norske-kommuner',
    path: '/guide/kommuneokonomi-norske-kommuner',
    getParentRoute: () => rootRouteImport,
  } as any)
const IMediaIndexRoute = IMediaIndexRouteImport.update({
  id: '/i-media/',
  path: '/i-media/',
  getParentRoute: () => rootRouteImport,
} as any)
const IMediaSlugRoute = IMediaSlugRouteImport.update({
  id: '/i-media/$slug',
  path: '/i-media/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirasjonIndexRoute = InspirasjonIndexRouteImport.update({
  id: '/inspirasjon/',
  path: '/inspirasjon/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirasjonSlugRoute = InspirasjonSlugRouteImport.update({
  id: '/inspirasjon/$slug',
  path: '/inspirasjon/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PublikasjonerIndexRoute = PublikasjonerIndexRouteImport.update({
  id: '/publikasjoner/',
  path: '/publikasjoner/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublikasjonerParamRoute = PublikasjonerParamRouteImport.update({
  id: '/publikasjoner/$param',
  path: '/publikasjoner/$param',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportSlugRoute = RapportSlugRouteImport.update({
  id: '/rapport/$slug',
  path: '/rapport/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportarkivIndexRoute = RapportarkivIndexRouteImport.update({
  id: '/rapportarkiv/',
  path: '/rapportarkiv/',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportarkivYearRoute = RapportarkivYearRouteImport.update({
  id: '/rapportarkiv/$year',
  path: '/rapportarkiv/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaSlugRoute = TemaSlugRouteImport.update({
  id: '/tema/$slug',
  path: '/tema/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/interkommunalt-samarbeid-kartlegging': typeof InterkommunaltSamarbeidKartleggingRoute
  '/kommuneokonomi-radgivning': typeof KommuneokonomiRadgivningRoute
  '/om-oss': typeof OmOssRoute
  '/personvern': typeof PersonvernRoute
  '/takk': typeof TakkRoute
  '/eksperter/roger-antonsen': typeof EksperterRogerAntonsenRoute
  '/fagomrader/$slug': typeof FagomraderSlugRoute
  '/guide/interkommunalt-samarbeid-norge': typeof GuideInterkommunaltSamarbeidNorgeRoute
  '/guide/kommuneokonomi-norske-kommuner': typeof GuideKommuneokonomiNorskeKommunerRoute
  '/i-media/$slug': typeof IMediaSlugRoute
  '/inspirasjon/$slug': typeof InspirasjonSlugRoute
  '/publikasjoner/$param': typeof PublikasjonerParamRoute
  '/rapport/$slug': typeof RapportSlugRoute
  '/rapportarkiv/$year': typeof RapportarkivYearRoute
  '/tema/$slug': typeof TemaSlugRoute
  '/i-media/': typeof IMediaIndexRoute
  '/inspirasjon/': typeof InspirasjonIndexRoute
  '/publikasjoner/': typeof PublikasjonerIndexRoute
  '/rapportarkiv/': typeof RapportarkivIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/interkommunalt-samarbeid-kartlegging': typeof InterkommunaltSamarbeidKartleggingRoute
  '/kommuneokonomi-radgivning': typeof KommuneokonomiRadgivningRoute
  '/om-oss': typeof OmOssRoute
  '/personvern': typeof PersonvernRoute
  '/takk': typeof TakkRoute
  '/eksperter/roger-antonsen': typeof EksperterRogerAntonsenRoute
  '/fagomrader/$slug': typeof FagomraderSlugRoute
  '/guide/interkommunalt-samarbeid-norge': typeof GuideInterkommunaltSamarbeidNorgeRoute
  '/guide/kommuneokonomi-norske-kommuner': typeof GuideKommuneokonomiNorskeKommunerRoute
  '/i-media/$slug': typeof IMediaSlugRoute
  '/inspirasjon/$slug': typeof InspirasjonSlugRoute
  '/publikasjoner/$param': typeof PublikasjonerParamRoute
  '/rapport/$slug': typeof RapportSlugRoute
  '/rapportarkiv/$year': typeof RapportarkivYearRoute
  '/tema/$slug': typeof TemaSlugRoute
  '/i-media': typeof IMediaIndexRoute
  '/inspirasjon': typeof InspirasjonIndexRoute
  '/publikasjoner': typeof PublikasjonerIndexRoute
  '/rapportarkiv': typeof RapportarkivIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/interkommunalt-samarbeid-kartlegging': typeof InterkommunaltSamarbeidKartleggingRoute
  '/kommuneokonomi-radgivning': typeof KommuneokonomiRadgivningRoute
  '/om-oss': typeof OmOssRoute
  '/personvern': typeof PersonvernRoute
  '/takk': typeof TakkRoute
  '/eksperter/roger-antonsen': typeof EksperterRogerAntonsenRoute
  '/fagomrader/$slug': typeof FagomraderSlugRoute
  '/guide/interkommunalt-samarbeid-norge': typeof GuideInterkommunaltSamarbeidNorgeRoute
  '/guide/kommuneokonomi-norske-kommuner': typeof GuideKommuneokonomiNorskeKommunerRoute
  '/i-media/$slug': typeof IMediaSlugRoute
  '/inspirasjon/$slug': typeof InspirasjonSlugRoute
  '/publikasjoner/$param': typeof PublikasjonerParamRoute
  '/rapport/$slug': typeof RapportSlugRoute
  '/rapportarkiv/$year': typeof RapportarkivYearRoute
  '/tema/$slug': typeof TemaSlugRoute
  '/i-media/': typeof IMediaIndexRoute
  '/inspirasjon/': typeof InspirasjonIndexRoute
  '/publikasjoner/': typeof PublikasjonerIndexRoute
  '/rapportarkiv/': typeof RapportarkivIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/interkommunalt-samarbeid-kartlegging'
    | '/kommuneokonomi-radgivning'
    | '/om-oss'
    | '/personvern'
    | '/takk'
    | '/eksperter/roger-antonsen'
    | '/fagomrader/$slug'
    | '/guide/interkommunalt-samarbeid-norge'
    | '/guide/kommuneokonomi-norske-kommuner'
    | '/i-media/$slug'
    | '/inspirasjon/$slug'
    | '/publikasjoner/$param'
    | '/rapport/$slug'
    | '/rapportarkiv/$year'
    | '/tema/$slug'
    | '/i-media/'
    | '/inspirasjon/'
    | '/publikasjoner/'
    | '/rapportarkiv/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/interkommunalt-samarbeid-kartlegging'
    | '/kommuneokonomi-radgivning'
    | '/om-oss'
    | '/personvern'
    | '/takk'
    | '/eksperter/roger-antonsen'
    | '/fagomrader/$slug'
    | '/guide/interkommunalt-samarbeid-norge'
    | '/guide/kommuneokonomi-norske-kommuner'
    | '/i-media/$slug'
    | '/inspirasjon/$slug'
    | '/publikasjoner/$param'
    | '/rapport/$slug'
    | '/rapportarkiv/$year'
    | '/tema/$slug'
    | '/i-media'
    | '/inspirasjon'
    | '/publikasjoner'
    | '/rapportarkiv'
  id:
    | '__root__'
    | '/'
    | '/cookies'
    | '/interkommunalt-samarbeid-kartlegging'
    | '/kommuneokonomi-radgivning'
    | '/om-oss'
    | '/personvern'
    | '/takk'
    | '/eksperter/roger-antonsen'
    | '/fagomrader/$slug'
    | '/guide/interkommunalt-samarbeid-norge'
    | '/guide/kommuneokonomi-norske-kommuner'
    | '/i-media/$slug'
    | '/inspirasjon/$slug'
    | '/publikasjoner/$param'
    | '/rapport/$slug'
    | '/rapportarkiv/$year'
    | '/tema/$slug'
    | '/i-media/'
    | '/inspirasjon/'
    | '/publikasjoner/'
    | '/rapportarkiv/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  InterkommunaltSamarbeidKartleggingRoute: typeof InterkommunaltSamarbeidKartleggingRoute
  KommuneokonomiRadgivningRoute: typeof KommuneokonomiRadgivningRoute
  OmOssRoute: typeof OmOssRoute
  PersonvernRoute: typeof PersonvernRoute
  TakkRoute: typeof TakkRoute
  EksperterRogerAntonsenRoute: typeof EksperterRogerAntonsenRoute
  FagomraderSlugRoute: typeof FagomraderSlugRoute
  GuideInterkommunaltSamarbeidNorgeRoute: typeof GuideInterkommunaltSamarbeidNorgeRoute
  GuideKommuneokonomiNorskeKommunerRoute: typeof GuideKommuneokonomiNorskeKommunerRoute
  IMediaSlugRoute: typeof IMediaSlugRoute
  InspirasjonSlugRoute: typeof InspirasjonSlugRoute
  PublikasjonerParamRoute: typeof PublikasjonerParamRoute
  RapportSlugRoute: typeof RapportSlugRoute
  RapportarkivYearRoute: typeof RapportarkivYearRoute
  TemaSlugRoute: typeof TemaSlugRoute
  IMediaIndexRoute: typeof IMediaIndexRoute
  InspirasjonIndexRoute: typeof InspirasjonIndexRoute
  PublikasjonerIndexRoute: typeof PublikasjonerIndexRoute
  RapportarkivIndexRoute: typeof RapportarkivIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interkommunalt-samarbeid-kartlegging': {
      id: '/interkommunalt-samarbeid-kartlegging'
      path: '/interkommunalt-samarbeid-kartlegging'
      fullPath: '/interkommunalt-samarbeid-kartlegging'
      preLoaderRoute: typeof InterkommunaltSamarbeidKartleggingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kommuneokonomi-radgivning': {
      id: '/kommuneokonomi-radgivning'
      path: '/kommuneokonomi-radgivning'
      fullPath: '/kommuneokonomi-radgivning'
      preLoaderRoute: typeof KommuneokonomiRadgivningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personvern': {
      id: '/personvern'
      path: '/personvern'
      fullPath: '/personvern'
      preLoaderRoute: typeof PersonvernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takk': {
      id: '/takk'
      path: '/takk'
      fullPath: '/takk'
      preLoaderRoute: typeof TakkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eksperter/roger-antonsen': {
      id: '/eksperter/roger-antonsen'
      path: '/eksperter/roger-antonsen'
      fullPath: '/eksperter/roger-antonsen'
      preLoaderRoute: typeof EksperterRogerAntonsenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fagomrader/$slug': {
      id: '/fagomrader/$slug'
      path: '/fagomrader/$slug'
      fullPath: '/fagomrader/$slug'
      preLoaderRoute: typeof FagomraderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/interkommunalt-samarbeid-norge': {
      id: '/guide/interkommunalt-samarbeid-norge'
      path: '/guide/interkommunalt-samarbeid-norge'
      fullPath: '/guide/interkommunalt-samarbeid-norge'
      preLoaderRoute: typeof GuideInterkommunaltSamarbeidNorgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/kommuneokonomi-norske-kommuner': {
      id: '/guide/kommuneokonomi-norske-kommuner'
      path: '/guide/kommuneokonomi-norske-kommuner'
      fullPath: '/guide/kommuneokonomi-norske-kommuner'
      preLoaderRoute: typeof GuideKommuneokonomiNorskeKommunerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i-media/': {
      id: '/i-media/'
      path: '/i-media'
      fullPath: '/i-media/'
      preLoaderRoute: typeof IMediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i-media/$slug': {
      id: '/i-media/$slug'
      path: '/i-media/$slug'
      fullPath: '/i-media/$slug'
      preLoaderRoute: typeof IMediaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspirasjon/': {
      id: '/inspirasjon/'
      path: '/inspirasjon'
      fullPath: '/inspirasjon/'
      preLoaderRoute: typeof InspirasjonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspirasjon/$slug': {
      id: '/inspirasjon/$slug'
      path: '/inspirasjon/$slug'
      fullPath: '/inspirasjon/$slug'
      preLoaderRoute: typeof InspirasjonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publikasjoner/': {
      id: '/publikasjoner/'
      path: '/publikasjoner'
      fullPath: '/publikasjoner/'
      preLoaderRoute: typeof PublikasjonerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publikasjoner/$param': {
      id: '/publikasjoner/$param'
      path: '/publikasjoner/$param'
      fullPath: '/publikasjoner/$param'
      preLoaderRoute: typeof PublikasjonerParamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapport/$slug': {
      id: '/rapport/$slug'
      path: '/rapport/$slug'
      fullPath: '/rapport/$slug'
      preLoaderRoute: typeof RapportSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapportarkiv/': {
      id: '/rapportarkiv/'
      path: '/rapportarkiv'
      fullPath: '/rapportarkiv/'
      preLoaderRoute: typeof RapportarkivIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapportarkiv/$year': {
      id: '/rapportarkiv/$year'
      path: '/rapportarkiv/$year'
      fullPath: '/rapportarkiv/$year'
      preLoaderRoute: typeof RapportarkivYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/$slug': {
      id: '/tema/$slug'
      path: '/tema/$slug'
      fullPath: '/tema/$slug'
      preLoaderRoute: typeof TemaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  InterkommunaltSamarbeidKartleggingRoute:
    InterkommunaltSamarbeidKartleggingRoute,
  KommuneokonomiRadgivningRoute: KommuneokonomiRadgivningRoute,
  OmOssRoute: OmOssRoute,
  PersonvernRoute: PersonvernRoute,
  TakkRoute: TakkRoute,
  EksperterRogerAntonsenRoute: EksperterRogerAntonsenRoute,
  FagomraderSlugRoute: FagomraderSlugRoute,
  GuideInterkommunaltSamarbeidNorgeRoute:
    GuideInterkommunaltSamarbeidNorgeRoute,
  GuideKommuneokonomiNorskeKommunerRoute:
    GuideKommuneokonomiNorskeKommunerRoute,
  IMediaSlugRoute: IMediaSlugRoute,
  InspirasjonSlugRoute: InspirasjonSlugRoute,
  PublikasjonerParamRoute: PublikasjonerParamRoute,
  RapportSlugRoute: RapportSlugRoute,
  RapportarkivYearRoute: RapportarkivYearRoute,
  TemaSlugRoute: TemaSlugRoute,
  IMediaIndexRoute: IMediaIndexRoute,
  InspirasjonIndexRoute: InspirasjonIndexRoute,
  PublikasjonerIndexRoute: PublikasjonerIndexRoute,
  RapportarkivIndexRoute: RapportarkivIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
